### ISSUE TITLE
Horrific popping sounds in Wine with 1.19

### ISSUE THREAD

**Issue by tannisroot** [kcat/openal-soft#226]
Hi, after upgrading openal package to 1.19 (on Arch, from official repositories), I get absolutely horrific popping sounds when I use a game in Wine (staging-3.15). Demonstration (not my video): https://streamable.com/mvy3c
Downgrading back to 1.18 gets rid of this. Also seems to happen to a lot of people that I know, so it's not just me.
I am very sorry for this kind of low-quality bug report, but if it's needed, what information can I provide to help fix this (if it's an issue on your end of course) and how?

**Comment by delamorte** [comment]
Can confirm on Arch, wine-staging 3.15 (also tried 3.14, both staging and normal) and openal 1.19.0-1 running just alsa. Downgrading to 1.18.2-2 fixed it. Tried installing pulseaudio but didn't help. For me I had issues with Divinity Original Sin 2 DefEd and GTA V, some other games worked fine without crackling.

**Comment by kcat** [comment]
Given that it doesn't affect normal (non-WIne) apps, it would seem to be an issue with the way Wine is using it. It would help if you could find the commonality between the affected apps, and try to trace it through to see what's misbehaving. A regular "popping" sound during playback may suggest an issue with streaming.

**Comment by shmerl** [comment]
@tannisroot: If it's a Wine specific issue, it's probably good to open a Wine bug about it as well.

**Comment by Sporif** [comment]
I've tried building  [openal-git](https://aur.archlinux.org/packages/openal-git/) to see which commit caused this issue, here's what I found:

| Status  | Version | Date |
|---|---|---|
| good | 1.18.1.r464.gd85ddf8a  |Mar 27 |
| semi | 1.18.1.r465.g5aecce5a | Mar 28 |
| semi | 1.18.1.r480.g414b56ed | Apr 02 |
| bad | 1.18.1.r481.g869637af | Apr 03 |

good = Perfect sound
semi = Crackling when sounds play
bad = Constant popping in the background + Crackling when sounds play

**Comment by tannisroot** [comment]
I've created a wine bug report too: https://bugs.winehq.org/show_bug.cgi?id=45838

**Comment by Glog78** [comment]
It's not only wine. A good example game is Hyper Light Drifter. Right when you enter a new game.

**Comment by Raulshc** [comment]
I also confirm the bug for native windows systems and 32bit ioq3 engines (ioquake3 and iortcw) and 32bit dhewm3 engine. More than horrible sounds are "sound glitches". Using a half-interval search on the git history I have verified that the bug was introduced in the commit 5aecce5a0dfb7784bfa3cc72642255872e0a4061. @kcat, take a look at this commit.

**Comment by kcat** [comment]
Hmm, certainly odd for it to only affect 32-bit builds. However, I think I found the problem and it should be fixed now with commit 8bacb5dfb8ef910586fcf5b5cd89526ec81061e8. The issue was the current buffer's sample offset was being modified incorrectly when stepping through completed buffer queue entries. Rather than being offset by the number of samples in the completed queue entry, it was offset by the number of samples in the now-current queue entry. It's not an issue when all the queue entries have the same size, but is a problem when the entries have varying sizes, causing jumps or temporarily negative buffer offsets.

**Comment by shmerl** [comment]
So this should go out in new point release?

**Comment by kcat** [comment]
Yes, that commit will be included in an upcoming 1.19.1 release.

**Comment by shmerl** [comment]
I hope you'll make it soon, so distros could pick it up to fix this.

**Comment by Raulshc** [comment]
Commit 8bacb5dfb8ef910586fcf5b5cd89526ec81061e8 works fine for me, the gliches have disappeared and the sound is clean now. Sorry for my description, the tests were performed with 32 bit builds on 32 bit windows systems only, the 64 bit version should also be affected.

@tannisroot, @delamorte Can you verify that the bug has been fixed?

**Comment by tannisroot** [comment]
Tried openal-git and lib32-openal-git packages from AUR, I don't experience any issues anymore.
I guess I can close it now. But if somebody still experiences this, let me know and I will re-open.

**Comment by shmerl** [comment]
Can you please make a point release with this bug fix? Lot's of distros keep pulling the buggy version.

**Comment by kcat** [comment]
1.19.1 is now available with this fix.

**Comment by shmerl** [comment]
Thanks!

**Comment by hollunder** [comment]
I'm not sure this is really gone in 1.19.1.
After approximately three hours all sound is severely distorted in any WINE game.
This issue started to appear with 1.19.0.

**Comment by kcat** [comment]
What audio system do you use (ALSA, PulseAudio, OSS, Jack, ...)? Are you using vanilla Wine, Proton, or Wine with some custom API wrappers? Does it happen in Wine games that don't (implicitly or explicitly) use OpenAL?

I remember a case of a bug that would cause issues with playback after about 5 hours seemingly due to an integer overflow in ALSA. That it starts after a few hours of regular use suggests the problem is a bit deeper than OpenAL Soft's mixer; maybe some timing issue with the audio system that OpenAL Soft starts stumbling over, or maybe some issue relating to the audio system interacting with Wine's audio wrapper interacting with OpenAL Soft.

**Comment by hollunder** [comment]
I use PulseAudio and sometimes JACK on top of PulseAudio (when I'm streaming). ALSA is always involved on the driver level (snd_usb_audio).

~/.openalrc contains:
```
frequency = 48000
drivers=pulse,alsa

[pulse]
allow-moves=true
```

Regarding WINE and games it's hard to say as I haven't noticed any configuration where it doesn't happen. I play most games using WINE-Staging from Arch (so usually latest version).
It also happens for example with Witcher 3 using DXVK or with XCOM (2003) with just WINE-Staging. I don't know how to tell which games use OpenAL and was assuming all of them do.
I'll try to experiment with different WINE variants and pay closer attention to hopefully narrow it down that way.

**Comment by hollunder** [comment]
I experimented a bit today and could narrow it down.
I had XCOM: Enemy Within running with WINE 3.20 for 7.5 hours and no crackling appeared.
Afterwards I ran it with WINE-Staging 3.20 and pretty much exactly 3 hours (3-3.25 h) later the crackling started.
So this looks like some interaction between OpenAL 1.19 and WINE-Staging going wrong. I'm reasonably sure that this problem didn't show with OpenAL 1.18 but have yet to verify that.

**Comment by shmerl** [comment]
> So this looks like some interaction between OpenAL 1.19 and WINE-Staging going wrong

1.19 is the buggy one. Or are you testing 1.19.1?

**Comment by kcat** [comment]
> I had XCOM: Enemy Within running with WINE 3.20 for 7.5 hours and no crackling appeared.
> Afterwards I ran it with WINE-Staging 3.20 and pretty much exactly 3 hours (3-3.25 h) later the crackling started.

Or perhaps an issue with Wine Staging itself. Check to see if it happens with apps that don't use OpenAL Soft (neither XAudio or anything else that uses OpenAL directly or indirectly). If it is only with OpenAL Soft, check with 1.18.2.

**Comment by hollunder** [comment]
The 1.18.2 test is underway.
It's not obvious to me what does and doesn't use OpenAL through WINE. Can you name an example I can try or how to find out what does or doesn't use OpenAL?

**Comment by kcat** [comment]
Anything using DirectSound doesn't (Oblivion or Fallout 3, for example), unless you're using something like DSOAL at least. For more modern (post-WinXP) games, the ones that use an engine that skips over XAudio and implement its own audio processing, interfacing directly with WASAPI/MMDeviceAPI... though I can't give specific examples of games that I know do that.

**Comment by hollunder** [comment]
Thanks, I should have a (hopefully functional) installation of these games lying around.
Apparently XAudio2 was released in 2008 and Xaudio 1 was XBox 360 only, so any game released for Windows before 2008 should also work, correct? Just wondering because I have plenty of older games that are far easier to get to work than those Bethesda games.
I come back with test results this evening.

**Comment by hollunder** [comment]
Alright, todays test results are in:
XCOM: Enemy Within, wine-staging, OpenAL 1.18.2, 7 hours and no crackling
Fallout 3, wine-staging, OpenAL 1.19.1, 7 hours and no crackling 
So to me the testing done so far suggests an interaction between wine-staging and OpenAL 1.19.1.

**Comment by shmerl** [comment]
Try to test it without staging first.

**Comment by hollunder** [comment]
I did that yesterday, see a few comments back.
>  I had XCOM: Enemy Within running with WINE 3.20 for 7.5 hours and no crackling appeared.

**Comment by shmerl** [comment]
Yeah, so sounds like a staging regression.
