### ISSUE TITLE
Stack overflow error

### ISSUE THREAD

**Issue by hsdk123** [kcat/openal-soft#407]
Hi, I get the following error when using openal32.dll
```
Exception thrown at 0x00007FFB2B4DBCF8 (OpenAL32.dll) in LightApp.exe: 0xC00000FD: Stack overflow (parameters: 0x0000000000000001, 0x000000244CA73000).
Unhandled exception at 0x00007FFB2B4DBCF8 (OpenAL32.dll) in LightApp.exe: 0xC00000FD: Stack overflow (parameters: 0x0000000000000001, 0x000000244CA73000).
```
The stack trace points the culprit being
```
alignas(16) const auto bsinc12_table = GenerateBSincCoeffs<bsinc12_hdr.total_size>(bsinc12_hdr);
```
and then
```
constexpr auto GenerateBSincCoeffs(const BSincHeader hdr)
```
I'm building through cmake and vs 2019.
This only occurs when building master, does not occur when building
```
28d2294b0782d47f0be9e1479e7eb9ff91ae54f0
```

**Comment by hsdk123** [comment]
I can also confirm this working for `a5b81672803951980b3b2aa7304e1fe69dd0325a`

**Comment by kcat** [comment]
Can you try with commit 25464b22107d9d1057e9835718fef1913873f367? That function should use significantly less stack now.

**Comment by hsdk123** [comment]
Still seems to give the same error:
```
Unhandled exception at 0x00007FFB2B4DBAF8 (OpenAL32.dll) in LightApp.exe: 0xC00000FD: Stack overflow (parameters: 0x0000000000000001, 0x000000576CC03000).
```

**Comment by kcat** [comment]
How big is the stack size for global initialization? The function shouldn't be using more than 200KB, which while rather high, shouldn't be prohibitively high.

The only other way I can currently think to handle this would either waste memory (a global array that would stick around when it's no longer needed), or prevent the function from being constexpr (heap allocating it).

**Comment by hsdk123** [comment]
Stack size seems to be by default 1MB, it might be that coupled together with other libraries, etc. 200kb ends up being too large. I'm unsure what's exactly happening.

**Comment by kcat** [comment]
The initialization functions should be called in series, one after another, so any other libraries shouldn't affect the amount of stack available. The only things I can think of is if the library is being loaded at runtime (via `LoadLibrary`) where a bunch of stack is already used when the call is made. Or the CRT initialization uses a whole bunch of stack itself while calling the initialization functions (which would be odd for it to use so much). Or initialization doesn't have access to a full stack for some reason.

In any case, commit 2fcc3f38876ec64395841b3ef87c8786fab59c44 now dynamically allocates the array, so that should fix it.

**Comment by hsdk123** [comment]
Thanks, I've tried with 2fcc3f3 and it looks like it still crashes with the same error. I've been trying to debug the situation and the stack overflow error seems to occur after
```
alignas(16) const auto bsinc12_table = GenerateBSincCoeffs<bsinc12_hdr.total_size>(bsinc12_hdr);
```
and immediately as we step into
```
alignas(16) const auto bsinc24_table = GenerateBSincCoeffs<bsinc24_hdr.total_size>(bsinc24_hdr);
```
I've decided to go a bit further, and visual studio static analysis seems to state that the functions are using much more than 200kb of stack even after the change.

![image](https://user-images.githubusercontent.com/4100142/78681065-424fd600-78ba-11ea-9432-c09401a70653.png)

![image](https://user-images.githubusercontent.com/4100142/78681162-5f84a480-78ba-11ea-8d15-4f6cb4b63580.png)

https://github.com/kcat/openal-soft/blob/master/common/bsinc_tables.cpp#L251

I think it may also be due to this array being allocated on the stack.

**Comment by kcat** [comment]
Well, this is getting curious. I was expecting named return value optimization (NRVO) to kick in to elide the copy, avoiding the stack by initializing it in-place in the global memory area. But it seems that's [explicitly forbidden](https://en.cppreference.com/w/cpp/language/copy_elision):
"In constant expression and constant initialization, return value optimization (RVO) is guaranteed, however, named return value optimization (NRVO) is forbidden"

I'm not sure if that's actually what's going on here, but either way, commit efed43123763a21aaa61f6e13e5a4578f5daf78b should avoid that stack array too.

**Comment by hsdk123** [comment]
Thanks, I can confirm this solves the issue!
And now to see if that removal of native tools also helps with the Android Builds on msvc....
